config/routes.rb
Rails.application.routes.draw do
  get 'pages/terms'
  get 'pages/about'
  get 'home/index'
  get 'contacts' => 'contacts#new'
  get 'terms' => 'pages#terms'
  resources :articles do
    resources :comments
  end
  resource :contacts, only: [:create] #Добавляем для контроллера маршруты только для указанных методов
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :comments
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :email, presence: true
  validates :message, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def new
      # @article = Article.new
      # render plain: params[:article].inspect
  end

  def index
    @article = Article.all
  end

  def show
   @article = Article.find(params[:id])
  end

  def create
    @article = Article.new(article_params)
     if @article.valid?
       @article.save
       # render plain: "OK"
        redirect_to @article
     else
       render action: 'new'
     end
  end

  def edit
      @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
        # redirect_to @article #Переводит на articles#show
        render plain: "OK"
    else
      render action: 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to articles_path
  end
  private

  def article_params
   params.require(:article).permit(:title, :text)
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
  end

  def create
    @contact = Contact.new(contact_params)
     if @contact.valid?
       @contact.save
     else
       render action: 'new'
     end
  end

  private

  def contact_params
   params.require(:contact).permit(:email, :message)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def terms
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/edit.html.erb
<h1>Edit article</h1>

<%= form_for :article, local: true, url: article_path(@article), method: :put do |f| %>
  <p><%= f.label :title %>
  <%= f.text_field :title %></p>

  <p><%= f.label :text %>
  <%= f.text_area :text %></p>

  <p><%= f.submit 'жыыыыык'%></p>
<% end %>

<a href="/articles">Show all articles</a>
</br>
<%= link_to 'Show all articles', articles_path %>

app/views/articles/index.html.erb
<h1>Article list :</h1>

<div class="">
  <% @article.each do |item|%>
  <p>Наименование : <%= item.title %>, Текст : <%= item.text %> <%= link_to 'Show', article_path(item)%> |
    <%= link_to 'Edit', edit_article_path(item)%> | <%= link_to 'Delete', article_path(item), method: :delete, data: {confirm: 'Are you shure?'} %></p>
  <% end %>
</div>

app/views/articles/new.html.erb
<h1>New article</h1>


<%= form_for :article, local: true, url: articles_path do |f| %>

    <%= f.label :title %><br/>
    <%= f.text_field :title %><br/>

    <%= f.label :text %><br/>
    <%= f.text_area :text %><br/>

    <%= f.submit 'Жопс' %>

<% end %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>

<p><%= @article.text %></p>

app/views/contacts/new.html.erb
<h2>Contact us</h2>

<%= form_for :contact, local: true, url: contacts_path do |f| %>
  <p>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :message %>
    <%= f.text_area :message %>
  </p>

  <p>
    <%= f.submit 'Send message' %>
  </p>

<% end %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsBlog2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/terms.html.erb
<h1>Pages#terms</h1>
<p>Find me in app/views/pages/terms.html.erb</p>